# Generated by Django 4.2.3 on 2026-03-27 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0002_choice_submission_question_choice_question'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='grad_point',
            new_name='grade',
        ),
    ]
